# Generated by Django 2.1.7 on 2019-03-26 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('credits_earned', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=20)),
                ('credits_req', models.IntegerField()),
                ('related_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaunchScreen.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Selection_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_load', models.IntegerField()),
                ('avg_starting_salary', models.CharField(choices=[('30,000 - 50,000', 'low'), ('50,000 - 80,000', 'med'), ('80,000+', 'high')], max_length=20)),
                ('interest_1', models.CharField(choices=[('Technology', 'tech'), ('Healthcare', 'health'), ('Artistic Expression', 'art'), ('Mathematics', 'math'), ('Science', 'science')], max_length=20)),
                ('interest_2', models.CharField(choices=[('Exercise', 'exercise'), ('Travel', 'travel'), ('Hands-on', 'manual'), ('Critical Thinking', 'crit_think')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='related_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaunchScreen.Major'),
        ),
    ]
