# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_load', models.IntegerField()),
                ('avg_starting_salary', models.CharField(choices=[('30,000 - 50,000', 'low'), ('50,000 - 80,000', 'med'), ('80,000+', 'high')], default='med', max_length=20, unique=True)),
                ('interest_1', models.CharField(choices=[('Technology', 'tech'), ('Healthcare', 'health'), ('Artistic Expression', 'art'), ('Mathematics', 'math'), ('Science', 'science')], max_length=20, unique=True)),
                ('interest_2', models.CharField(choices=[('Exercise', 'exercise'), ('Travel', 'travel'), ('Hands-on', 'manual'), ('Critical Thinking', 'crit_think')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=20)),
                ('credits_req', models.IntegerField()),
                ('avg_starting_salary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='launchscreen.Interests', to_field='avg_starting_salary')),
                ('major_major_interest_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_major_interest_tag', to='launchscreen.Interests', to_field='interest_1')),
                ('major_minor_interest_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_minor_interest_tag', to='launchscreen.Interests', to_field='interest_2')),
                ('related_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='launchscreen.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Uni_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('credits_earned', models.IntegerField()),
                ('class_major_interest_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_major_interest_tag', to='launchscreen.Interests', to_field='interest_2')),
                ('class_minor_interest_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_minor_interest_tag', to='launchscreen.Interests', to_field='interest_2')),
                ('related_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='launchscreen.Major')),
            ],
        ),
    ]
