# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchscreen', '0006_auto_20190425_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uni_class',
            name='avg_starting_salary',
        ),
    ]
