# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchscreen', '0007_remove_uni_class_avg_starting_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_name',
            field=models.CharField(max_length=100),
        ),
    ]
