# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-29 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launchscreen', '0008_auto_20190425_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=600)),
                ('abbreviation', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('credits_earned', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='primaryInterests',
        ),
        migrations.DeleteModel(
            name='secondaryInterests',
        ),
        migrations.RemoveField(
            model_name='uni_class',
            name='related_major',
        ),
        migrations.RemoveField(
            model_name='major',
            name='interest_1',
        ),
        migrations.RemoveField(
            model_name='major',
            name='interest_2',
        ),
        migrations.DeleteModel(
            name='Uni_Class',
        ),
        migrations.AddField(
            model_name='course',
            name='related_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='launchscreen.Major'),
        ),
        migrations.AddField(
            model_name='course',
            name='related_primary_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='launchscreen.PrimaryInterest'),
        ),
        migrations.AddField(
            model_name='course',
            name='related_secondary_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='launchscreen.SecondaryInterest'),
        ),
        migrations.AddField(
            model_name='major',
            name='related_primary_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='launchscreen.PrimaryInterest'),
        ),
        migrations.AddField(
            model_name='major',
            name='related_secondary_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='launchscreen.SecondaryInterest'),
        ),
    ]
