# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-29 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchscreen', '0010_auto_20190429_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='tag_weight',
            field=models.IntegerField(default=0),
        ),
    ]
