# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchscreen', '0012_auto_20190429_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primaryinterest',
            old_name='selected',
            new_name='checked',
        ),
        migrations.RemoveField(
            model_name='course',
            name='related_secondary_interest',
        ),
        migrations.RemoveField(
            model_name='major',
            name='related_secondary_interest',
        ),
        migrations.DeleteModel(
            name='SecondaryInterest',
        ),
    ]
