# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchscreen', '0015_course_gre_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='credits_req',
        ),
    ]
