# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launchscreen', '0017_major_credits_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='related_major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='launchscreen.Major'),
        ),
    ]
